# docker-compose.yml
services:
  web:
    image: githubyumao/Blora-Manager-web:latest
    ports:
      - "23333:23333"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - <CHANGE_ME_TO_INSTALL_PATH>/web/data:/opt/Blora-Manager/web/data
      - <CHANGE_ME_TO_INSTALL_PATH>/web/logs:/opt/Blora-Manager/web/logs

  daemon:
    image: githubyumao/Blora-Manager-daemon:latest
    restart: unless-stopped
    network_mode: host # if you want run instance in daemon container
    # ports:
    #   - "24444:24444"
    environment:
      - MCSM_DOCKER_WORKSPACE_PATH=<CHANGE_ME_TO_INSTALL_PATH>/daemon/data/InstanceData
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - <CHANGE_ME_TO_INSTALL_PATH>/daemon/data:/opt/Blora-Manager/daemon/data
      - <CHANGE_ME_TO_INSTALL_PATH>/daemon/logs:/opt/Blora-Manager/daemon/logs
      - /var/run/docker.sock:/var/run/docker.sock
